# Generated by Django 3.0.5 on 2022-09-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220914_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='date',
        ),
    ]
