# Generated by Django 3.0.5 on 2022-09-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20220921_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidOffer', to='auctions.Bids'),
        ),
    ]
