# Generated by Django 3.0.5 on 2022-09-21 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listings_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='price',
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Listings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='currentPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
