# Generated by Django 3.0.5 on 2022-09-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20220921_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='startingPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
